### ISSUE TITLE
Version 1.2 not compatible with Contao 4.4 anymore

### ISSUE THREAD

**Issue by leonexcc** [contao/test-case#2]
"contao/core-bundle": "^4.4" should be "contao/core-bundle": "^4.5" since this is not compatible with Contao 4.4 anymore.

And shouldn't be the dependency to phpunit 7 in the composer.json?

**Comment by leofeyer** [comment]
Fixed in d6295e0830419ef8dfbf245e8805a355662af634. Thank you @leonexcc.
