### ISSUE TITLE
Consider dropping the app's var folder in FunctionalTestCase#tearDownAfterClass

### ISSUE THREAD

**Issue by m-vo** [contao/test-case#6]
After running functional tests, the `%projectDir%/var` folder will contain log/cache/assets/... entries which could be cleaned up.

**Comment by leofeyer** [comment]
That would not really help, as other tools such as PhpStan also boot up Symfony and fill the `var` folder. The only solution so far was to ignore the folder in the `.gitignore` file of the core bundle.

https://github.com/contao/contao/blob/master/core-bundle/.gitignore

**Comment by m-vo** [comment]
Sounds legit to me. Imo we can close this then.
